name: Publish to npm

on:
  push:
    tags:
      - 'v*'
      - '!vscode-v*'  # Exclude vscode tags
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.4)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for npm provenance

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Run tests
        run: pnpm -r run test --run

      - name: Publish @specmind/format
        working-directory: packages/format
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks
        continue-on-error: true

      - name: Publish @specmind/core
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks
        continue-on-error: true

      - name: Publish specmind (CLI)
        working-directory: packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks
        continue-on-error: true
